export const icons = [
  { id: 1,  src: require("./Images/Facebook Messenger.jpg"), title: "Messenger",},
  { id: 2,  src: require("./Images/Facebook.png"),           title: "Facebook" },
  { id: 3,  src: require("./Images/Google Drive.jpg"),       title: "Google Drive" },
  { id: 4,  src: require("./Images/Instagram.jpg"),          title: "Instagram" },
  { id: 5,  src: require("./Images/SHAREit.jpg"),            title: "SHAREit" },
  { id: 6,  src: require("./Images/Skype.png"),              title: "Skype" },
  { id: 7,  src: require("./Images/Telegram.jpg"),           title: "Telegram" },
  { id: 8,  src: require("./Images/TikTok.png"),             title: "TikTok" },
  { id: 9,  src: require("./Images/Twitter.png"),            title: "Twitter" },
  { id: 10, src: require("./Images/WhatsApp.jpg"),           title: "WhatsApp" },
  { id: 11,  src: require("./Images/Amazon.png"),            title: "Amazon" },
  { id: 12,  src: require("./Images/Amex.png"),              title: "Amex" },
  { id: 13,  src: require("./Images/Calculator.png"),        title: "Calculator" },
  { id: 14,  src: require("./Images/Calender.png"),          title: "Calender" },
  { id: 15,  src: require("./Images/Camera.jpg"),            title: "Camera" },
  { id: 16,  src: require("./Images/Canvas.png"),            title: "Canvas" },
  { id: 17,  src: require("./Images/Cash App.png"),          title: "Cash App" },
  { id: 18,  src: require("./Images/Chase.png"),             title: "Chase" },
  { id: 19,  src: require("./Images/Chrome.jpg"),            title: "Chrome" },
  { id: 20,  src: require("./Images/Discover.png"),          title: "Discover" },
  { id: 21,  src: require("./Images/Email.png"),             title: "Email" },
  { id: 22,  src: require("./Images/Google Maps.jpg"),       title: "Google Maps" },
  { id: 23,  src: require("./Images/Hulu.jpg"),              title: "Hulu" },
  { id: 24,  src: require("./Images/LinkedIn.png"),          title: "LinkedIn" },
  { id: 25,  src: require("./Images/Messages.jpg"),          title: "Messages" },
  { id: 26,  src: require("./Images/Netflix.png"),           title: "Netflix" },
  { id: 27,  src: require("./Images/PayPal.jpg"),            title: "PayPal" },
  { id: 28,  src: require("./Images/Phone.png"),             title: "Phone" },
  { id: 29,  src: require("./Images/Photos.jpg"),            title: "Photos" },
  { id: 30,  src: require("./Images/Prime Video.jpg"),       title: "Prime Video" },
  { id: 31,  src: require("./Images/Settings.jpg"),          title: "Settings" },
  { id: 32,  src: require("./Images/Snapchat.png"),          title: "Snapchat" },
  { id: 33,  src: require("./Images/YouTube.png"),           title: "YouTube" },
  { id: 34,  src: require("./Images/Reddit.png"),            title: "Reddit" },
  { id: 35,  src: require("./Images/Games.jpg"),             title: "Games" },
  { id: 36,  src: require("./Images/Walmart.jpg"),           title: "Walmart" },
  { id: 37,  src: require("./Images/Delta Airlines.jpg"),    title: "Delta" },
  { id: 38,  src: require("./Images/Southwest Airlines.png"),title: "Southwest" },
  { id: 39,  src: require("./Images/Amazon Music.jpg"),      title: "Amazon Music" },
  { id: 40,  src: require("./Images/Word.jpg"),              title: "Word" },
  { id: 41,  src: require("./Images/Powerpoint.png"),        title: "Powerpoint" },
  { id: 42,  src: require("./Images/Excel.png"),             title: "Excel" },
];
